language: python
python:
    - "3.4"
    - "3.3"
    - "2.6"
    - "2.7"

env:
    - xpafydebug=1

install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
    - pip install coveralls > /dev/null

branches:
    only:
    - develop

before_script:
    - pwd
    - ls -l
    - coverage debug sys

script:
    coverage run --omit=/unittest2/ test.py

after_success:
    - coverage report
    - coveralls
