language: python
python:
    - "3.4"
    - "3.3"
    - "2.6"
    - "2.7"

install:
    - pip install coveralls > /dev/null

branches:
    only:
    - develop

env:
    - pafydebug=1
script:
    coverage run test.py

after_success:
    coveralls
