language: python
python:
    - "3.4"
    - "3.3"
    - "2.6"
    - "2.7"

install:
    - pip install coveralls

branches:
    only:
    - develop

script:
    coverage run test.py

after_success:
    coveralls
